/*
 * render_vk.c — Vulkan backend for render.h
 *
 * Replaces NITSHELL.DLL. Implements:
 *   render_init / render_shutdown
 *   render_begin_frame / render_end_frame
 *   render_set_palette / render_blit_indexed
 *
 * Architecture:
 *   - SDL2 owns the window and creates the VkSurfaceKHR via SDL_Vulkan_*
 *   - One graphics+present queue (same family preferred)
 *   - Double-buffered swapchain (mailbox if available, FIFO fallback)
 *   - One descriptor set: binding 0 = index texture, binding 1 = palette UBO
 *   - Fullscreen triangle drawn every frame; fragment shader expands palette
 *   - Staging buffer for index texture uploads (persistently mapped)
 *   - Palette UBO is host-coherent (direct memcpy, no barrier needed)
 */

#include "render.h"
#include "platform/platform.h"

#include <SDL2/SDL.h>
#include <SDL2/SDL_vulkan.h>
#include <vulkan/vulkan.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Embedded SPIR-V — generated by cmake/embed_spv.cmake */
#include "blit_vert_spv.h"
#include "blit_frag_spv.h"

/* -----------------------------------------------------------------------
 * Internal helpers
 * ----------------------------------------------------------------------- */

#define MAX_FRAMES_IN_FLIGHT 2

#define VK_CHECK(call)                                                        \
    do {                                                                      \
        VkResult _r = (call);                                                 \
        if (_r != VK_SUCCESS) {                                               \
            fprintf(stderr, "[render_vk] %s returned %d (%s:%d)\n",          \
                    #call, _r, __FILE__, __LINE__);                           \
            exit(1);                                                          \
        }                                                                     \
    } while (0)

static void vk_fatal(const char *msg)
{
    fprintf(stderr, "[render_vk] Fatal: %s\n", msg);
    exit(1);
}

/* -----------------------------------------------------------------------
 * State
 * ----------------------------------------------------------------------- */

static VkInstance               s_instance;
static VkSurfaceKHR             s_surface;
static VkPhysicalDevice         s_phys;
static VkDevice                 s_device;
static uint32_t                 s_gfx_family;
static uint32_t                 s_present_family;
static VkQueue                  s_gfx_queue;
static VkQueue                  s_present_queue;

static VkSwapchainKHR           s_swapchain;
static VkFormat                 s_sc_format;
static VkExtent2D               s_sc_extent;
static uint32_t                 s_sc_count;
static VkImage                 *s_sc_images;
static VkImageView             *s_sc_views;
static VkFramebuffer           *s_sc_fbs;

static VkRenderPass             s_render_pass;
static VkDescriptorSetLayout    s_dsl;
static VkPipelineLayout         s_pipeline_layout;
static VkPipeline               s_pipeline;
static VkDescriptorPool         s_desc_pool;
static VkDescriptorSet          s_desc_set;

static VkCommandPool            s_cmd_pool;
static VkCommandBuffer          s_cmd_bufs[MAX_FRAMES_IN_FLIGHT];
static VkSemaphore              s_sem_image_ready[MAX_FRAMES_IN_FLIGHT];
static VkSemaphore             *s_sem_render_done; /* [s_sc_count] — one per swapchain image */
static VkFence                  s_fence[MAX_FRAMES_IN_FLIGHT];
static uint32_t                 s_frame      = 0;
static uint32_t                 s_image_idx  = 0;

/* Index texture (8-bit, one byte per pixel) */
static VkImage                  s_idx_image;
static VkDeviceMemory           s_idx_memory;
static VkImageView              s_idx_view;
static VkSampler                s_sampler;
static VkBuffer                 s_idx_staging;
static VkDeviceMemory           s_idx_staging_mem;
static void                    *s_idx_staging_map;
static uint32_t                 s_idx_w = 0;
static uint32_t                 s_idx_h = 0;
static bool                     s_idx_first_upload = true;

/* Palette UBO: 256 × vec4, std140 = 4096 bytes */
#define PALETTE_UBO_SIZE (256 * 4 * sizeof(float))
static VkBuffer                 s_pal_buf;
static VkDeviceMemory           s_pal_mem;
static void                    *s_pal_map;

/* Pending uploads this frame */
static bool                     s_pending_palette = false;
static bool                     s_pending_blit    = false;

/* -----------------------------------------------------------------------
 * Memory helpers
 * ----------------------------------------------------------------------- */

static uint32_t find_memory_type(uint32_t filter, VkMemoryPropertyFlags flags)
{
    VkPhysicalDeviceMemoryProperties mp;
    vkGetPhysicalDeviceMemoryProperties(s_phys, &mp);
    for (uint32_t i = 0; i < mp.memoryTypeCount; i++)
        if ((filter & (1u << i)) &&
            (mp.memoryTypes[i].propertyFlags & flags) == flags)
            return i;
    vk_fatal("No suitable memory type");
    return 0;
}

static void make_buffer(VkDeviceSize size, VkBufferUsageFlags usage,
                        VkMemoryPropertyFlags props,
                        VkBuffer *buf, VkDeviceMemory *mem)
{
    VkBufferCreateInfo bi = {
        .sType       = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
        .size        = size,
        .usage       = usage,
        .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
    };
    VK_CHECK(vkCreateBuffer(s_device, &bi, NULL, buf));

    VkMemoryRequirements req;
    vkGetBufferMemoryRequirements(s_device, *buf, &req);

    VkMemoryAllocateInfo ai = {
        .sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
        .allocationSize  = req.size,
        .memoryTypeIndex = find_memory_type(req.memoryTypeBits, props),
    };
    VK_CHECK(vkAllocateMemory(s_device, &ai, NULL, mem));
    VK_CHECK(vkBindBufferMemory(s_device, *buf, *mem, 0));
}

static void make_image(uint32_t w, uint32_t h, VkFormat fmt,
                       VkImageUsageFlags usage, VkMemoryPropertyFlags props,
                       VkImage *img, VkDeviceMemory *mem)
{
    VkImageCreateInfo ii = {
        .sType         = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
        .imageType     = VK_IMAGE_TYPE_2D,
        .format        = fmt,
        .extent        = { w, h, 1 },
        .mipLevels     = 1,
        .arrayLayers   = 1,
        .samples       = VK_SAMPLE_COUNT_1_BIT,
        .tiling        = VK_IMAGE_TILING_OPTIMAL,
        .usage         = usage,
        .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
        .sharingMode   = VK_SHARING_MODE_EXCLUSIVE,
    };
    VK_CHECK(vkCreateImage(s_device, &ii, NULL, img));

    VkMemoryRequirements req;
    vkGetImageMemoryRequirements(s_device, *img, &req);

    VkMemoryAllocateInfo ai = {
        .sType           = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
        .allocationSize  = req.size,
        .memoryTypeIndex = find_memory_type(req.memoryTypeBits, props),
    };
    VK_CHECK(vkAllocateMemory(s_device, &ai, NULL, mem));
    VK_CHECK(vkBindImageMemory(s_device, *img, *mem, 0));
}

/* One-shot command buffer for transfers / layout transitions */
static VkCommandBuffer begin_one_time(void)
{
    VkCommandBufferAllocateInfo ai = {
        .sType              = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
        .commandPool        = s_cmd_pool,
        .level              = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
        .commandBufferCount = 1,
    };
    VkCommandBuffer cmd;
    vkAllocateCommandBuffers(s_device, &ai, &cmd);

    VkCommandBufferBeginInfo bi = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
        .flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT,
    };
    vkBeginCommandBuffer(cmd, &bi);
    return cmd;
}

static void end_one_time(VkCommandBuffer cmd)
{
    vkEndCommandBuffer(cmd);
    VkSubmitInfo si = {
        .sType              = VK_STRUCTURE_TYPE_SUBMIT_INFO,
        .commandBufferCount = 1,
        .pCommandBuffers    = &cmd,
    };
    vkQueueSubmit(s_gfx_queue, 1, &si, VK_NULL_HANDLE);
    vkQueueWaitIdle(s_gfx_queue);
    vkFreeCommandBuffers(s_device, s_cmd_pool, 1, &cmd);
}

static void transition_image_layout(VkCommandBuffer cmd, VkImage img,
                                    VkImageLayout from, VkImageLayout to)
{
    VkImageMemoryBarrier b = {
        .sType               = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
        .oldLayout           = from,
        .newLayout           = to,
        .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
        .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
        .image               = img,
        .subresourceRange    = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 },
    };

    VkPipelineStageFlags src_stage, dst_stage;

    if (from == VK_IMAGE_LAYOUT_UNDEFINED &&
        to   == VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL) {
        b.srcAccessMask = 0;
        b.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
        src_stage = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT;
        dst_stage = VK_PIPELINE_STAGE_TRANSFER_BIT;
    } else if (from == VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL &&
               to   == VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL) {
        b.srcAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
        b.dstAccessMask = VK_ACCESS_SHADER_READ_BIT;
        src_stage = VK_PIPELINE_STAGE_TRANSFER_BIT;
        dst_stage = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
    } else if (from == VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL &&
               to   == VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL) {
        b.srcAccessMask = VK_ACCESS_SHADER_READ_BIT;
        b.dstAccessMask = VK_ACCESS_TRANSFER_WRITE_BIT;
        src_stage = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT;
        dst_stage = VK_PIPELINE_STAGE_TRANSFER_BIT;
    } else {
        vk_fatal("Unsupported image layout transition");
        src_stage = dst_stage = 0;
    }

    vkCmdPipelineBarrier(cmd, src_stage, dst_stage, 0,
                         0, NULL, 0, NULL, 1, &b);
}

/* -----------------------------------------------------------------------
 * Instance
 * ----------------------------------------------------------------------- */

static bool layer_available(const char *name)
{
    uint32_t count = 0;
    vkEnumerateInstanceLayerProperties(&count, NULL);
    VkLayerProperties *props = malloc(count * sizeof(*props));
    vkEnumerateInstanceLayerProperties(&count, props);
    bool found = false;
    for (uint32_t i = 0; i < count; i++)
        if (strcmp(props[i].layerName, name) == 0) { found = true; break; }
    free(props);
    return found;
}

static void create_instance(SDL_Window *win)
{
    uint32_t sdl_ext_count = 0;
    SDL_Vulkan_GetInstanceExtensions(win, &sdl_ext_count, NULL);

    const char **exts = malloc((sdl_ext_count + 1) * sizeof(char *));
    SDL_Vulkan_GetInstanceExtensions(win, &sdl_ext_count, exts);
    uint32_t ext_count = sdl_ext_count;

    const char *validation_layer = "VK_LAYER_KHRONOS_validation";
    bool use_validation = false;

#ifdef I76_VULKAN_VALIDATION
    if (layer_available(validation_layer)) {
        use_validation = true;
        exts[ext_count++] = VK_EXT_DEBUG_UTILS_EXTENSION_NAME;
        fprintf(stdout, "[render_vk] Validation layers enabled.\n");
    } else {
        fprintf(stdout, "[render_vk] Validation layers not found "
                "(install vulkan-validation-layers). Running without.\n");
    }
#endif

    VkApplicationInfo app = {
        .sType              = VK_STRUCTURE_TYPE_APPLICATION_INFO,
        .pApplicationName   = "Interstate '76 Nitro Pack",
        .applicationVersion = VK_MAKE_VERSION(0, 1, 0),
        .pEngineName        = "i76",
        .engineVersion      = VK_MAKE_VERSION(0, 1, 0),
        .apiVersion         = VK_API_VERSION_1_0,
    };

    VkInstanceCreateInfo ci = {
        .sType                   = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO,
        .pApplicationInfo        = &app,
        .enabledExtensionCount   = ext_count,
        .ppEnabledExtensionNames = exts,
        .enabledLayerCount       = use_validation ? 1 : 0,
        .ppEnabledLayerNames     = use_validation ? &validation_layer : NULL,
    };

    VK_CHECK(vkCreateInstance(&ci, NULL, &s_instance));
    free(exts);
}

/* -----------------------------------------------------------------------
 * Physical device + queue families
 * ----------------------------------------------------------------------- */

static bool check_device(VkPhysicalDevice dev,
                         uint32_t *out_gfx, uint32_t *out_present)
{
    /* Queue families */
    uint32_t qf_count;
    vkGetPhysicalDeviceQueueFamilyProperties(dev, &qf_count, NULL);
    VkQueueFamilyProperties *qf = malloc(qf_count * sizeof(*qf));
    vkGetPhysicalDeviceQueueFamilyProperties(dev, &qf_count, qf);

    int gfx = -1, present = -1;
    for (uint32_t i = 0; i < qf_count; i++) {
        if (qf[i].queueFlags & VK_QUEUE_GRAPHICS_BIT) gfx = (int)i;
        VkBool32 ps = VK_FALSE;
        vkGetPhysicalDeviceSurfaceSupportKHR(dev, i, s_surface, &ps);
        if (ps) present = (int)i;
    }
    free(qf);
    if (gfx < 0 || present < 0) return false;

    /* VK_KHR_swapchain extension */
    uint32_t ec;
    vkEnumerateDeviceExtensionProperties(dev, NULL, &ec, NULL);
    VkExtensionProperties *ep = malloc(ec * sizeof(*ep));
    vkEnumerateDeviceExtensionProperties(dev, NULL, &ec, ep);
    bool has_sc = false;
    for (uint32_t i = 0; i < ec; i++)
        if (strcmp(ep[i].extensionName, VK_KHR_SWAPCHAIN_EXTENSION_NAME) == 0)
            { has_sc = true; break; }
    free(ep);
    if (!has_sc) return false;

    /* Swapchain has at least one format and one present mode */
    uint32_t fmt_count, pm_count;
    vkGetPhysicalDeviceSurfaceFormatsKHR(dev, s_surface, &fmt_count, NULL);
    vkGetPhysicalDeviceSurfacePresentModesKHR(dev, s_surface, &pm_count, NULL);
    if (!fmt_count || !pm_count) return false;

    *out_gfx     = (uint32_t)gfx;
    *out_present = (uint32_t)present;
    return true;
}

static void pick_device(void)
{
    uint32_t count;
    vkEnumeratePhysicalDevices(s_instance, &count, NULL);
    if (!count) vk_fatal("No Vulkan-capable GPU found");

    VkPhysicalDevice *devs = malloc(count * sizeof(*devs));
    vkEnumeratePhysicalDevices(s_instance, &count, devs);

    s_phys = VK_NULL_HANDLE;
    bool found_discrete = false;

    for (uint32_t i = 0; i < count; i++) {
        uint32_t g, p;
        if (!check_device(devs[i], &g, &p)) continue;

        VkPhysicalDeviceProperties props;
        vkGetPhysicalDeviceProperties(devs[i], &props);
        bool discrete = (props.deviceType == VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU);

        if (s_phys == VK_NULL_HANDLE || (!found_discrete && discrete)) {
            s_phys           = devs[i];
            s_gfx_family     = g;
            s_present_family = p;
            found_discrete   = discrete;
        }
    }
    free(devs);

    if (s_phys == VK_NULL_HANDLE) vk_fatal("No suitable GPU found");

    VkPhysicalDeviceProperties props;
    vkGetPhysicalDeviceProperties(s_phys, &props);
    fprintf(stdout, "[render_vk] GPU: %s\n", props.deviceName);
}

/* -----------------------------------------------------------------------
 * Logical device
 * ----------------------------------------------------------------------- */

static void create_device(void)
{
    float prio = 1.0f;
    uint32_t qci_count = 1;
    VkDeviceQueueCreateInfo qci[2] = {
        {
            .sType            = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
            .queueFamilyIndex = s_gfx_family,
            .queueCount       = 1,
            .pQueuePriorities = &prio,
        }
    };
    if (s_present_family != s_gfx_family) {
        qci[1] = (VkDeviceQueueCreateInfo){
            .sType            = VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO,
            .queueFamilyIndex = s_present_family,
            .queueCount       = 1,
            .pQueuePriorities = &prio,
        };
        qci_count = 2;
    }

    const char *exts[] = { VK_KHR_SWAPCHAIN_EXTENSION_NAME };

    VkDeviceCreateInfo ci = {
        .sType                   = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
        .queueCreateInfoCount    = qci_count,
        .pQueueCreateInfos       = qci,
        .enabledExtensionCount   = 1,
        .ppEnabledExtensionNames = exts,
    };
    VK_CHECK(vkCreateDevice(s_phys, &ci, NULL, &s_device));

    vkGetDeviceQueue(s_device, s_gfx_family,     0, &s_gfx_queue);
    vkGetDeviceQueue(s_device, s_present_family,  0, &s_present_queue);
}

/* -----------------------------------------------------------------------
 * Swapchain
 * ----------------------------------------------------------------------- */

static void create_swapchain(int win_w, int win_h)
{
    VkSurfaceCapabilitiesKHR caps;
    vkGetPhysicalDeviceSurfaceCapabilitiesKHR(s_phys, s_surface, &caps);

    /* Format — prefer BGRA8 sRGB */
    uint32_t fc;
    vkGetPhysicalDeviceSurfaceFormatsKHR(s_phys, s_surface, &fc, NULL);
    VkSurfaceFormatKHR *fmts = malloc(fc * sizeof(*fmts));
    vkGetPhysicalDeviceSurfaceFormatsKHR(s_phys, s_surface, &fc, fmts);

    /*
     * Prefer UNORM over SRGB. The original game fed raw palette byte values
     * directly to the display DAC with no gamma transform. SRGB would cause
     * the driver to apply gamma encoding to our already-display-ready palette
     * colours, making everything look wrong. UNORM writes them straight through.
     *
     * Both use VK_COLOR_SPACE_SRGB_NONLINEAR_KHR — that describes the monitor's
     * expected input encoding (sRGB/gamma), not a GPU-side transform.
     */
    VkSurfaceFormatKHR chosen = fmts[0];
    for (uint32_t i = 0; i < fc; i++) {
        if (fmts[i].colorSpace != VK_COLOR_SPACE_SRGB_NONLINEAR_KHR) continue;
        if (fmts[i].format == VK_FORMAT_B8G8R8A8_UNORM) { chosen = fmts[i]; break; }
        if (fmts[i].format == VK_FORMAT_R8G8B8A8_UNORM && chosen.format != VK_FORMAT_B8G8R8A8_UNORM)
            chosen = fmts[i];
    }
    free(fmts);
    s_sc_format = chosen.format;
    fprintf(stdout, "[render_vk] Swapchain format: %s\n",
            chosen.format == VK_FORMAT_B8G8R8A8_UNORM ? "B8G8R8A8_UNORM" :
            chosen.format == VK_FORMAT_R8G8B8A8_UNORM ? "R8G8B8A8_UNORM" :
            chosen.format == VK_FORMAT_B8G8R8A8_SRGB  ? "B8G8R8A8_SRGB (fallback — colours may be off)" :
            "other");

    /* Present mode — prefer mailbox (no tearing, low latency) */
    uint32_t pmc;
    vkGetPhysicalDeviceSurfacePresentModesKHR(s_phys, s_surface, &pmc, NULL);
    VkPresentModeKHR *pms = malloc(pmc * sizeof(*pms));
    vkGetPhysicalDeviceSurfacePresentModesKHR(s_phys, s_surface, &pmc, pms);

    VkPresentModeKHR pm = VK_PRESENT_MODE_FIFO_KHR;
    for (uint32_t i = 0; i < pmc; i++)
        if (pms[i] == VK_PRESENT_MODE_MAILBOX_KHR) { pm = pms[i]; break; }
    free(pms);

    /* Extent */
    if (caps.currentExtent.width != UINT32_MAX) {
        s_sc_extent = caps.currentExtent;
    } else {
        s_sc_extent = (VkExtent2D){
            .width  = (uint32_t)win_w,
            .height = (uint32_t)win_h,
        };
    }

    uint32_t img_count = caps.minImageCount + 1;
    if (caps.maxImageCount && img_count > caps.maxImageCount)
        img_count = caps.maxImageCount;

    VkSwapchainCreateInfoKHR sci = {
        .sType            = VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR,
        .surface          = s_surface,
        .minImageCount    = img_count,
        .imageFormat      = chosen.format,
        .imageColorSpace  = chosen.colorSpace,
        .imageExtent      = s_sc_extent,
        .imageArrayLayers = 1,
        .imageUsage       = VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT,
        .preTransform     = caps.currentTransform,
        .compositeAlpha   = VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR,
        .presentMode      = pm,
        .clipped          = VK_TRUE,
    };

    uint32_t qfi[2] = { s_gfx_family, s_present_family };
    if (s_gfx_family != s_present_family) {
        sci.imageSharingMode      = VK_SHARING_MODE_CONCURRENT;
        sci.queueFamilyIndexCount = 2;
        sci.pQueueFamilyIndices   = qfi;
    } else {
        sci.imageSharingMode = VK_SHARING_MODE_EXCLUSIVE;
    }

    VK_CHECK(vkCreateSwapchainKHR(s_device, &sci, NULL, &s_swapchain));

    vkGetSwapchainImagesKHR(s_device, s_swapchain, &s_sc_count, NULL);
    s_sc_images = malloc(s_sc_count * sizeof(*s_sc_images));
    vkGetSwapchainImagesKHR(s_device, s_swapchain, &s_sc_count, s_sc_images);

    s_sc_views = malloc(s_sc_count * sizeof(*s_sc_views));
    for (uint32_t i = 0; i < s_sc_count; i++) {
        VkImageViewCreateInfo vi = {
            .sType      = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
            .image      = s_sc_images[i],
            .viewType   = VK_IMAGE_VIEW_TYPE_2D,
            .format     = s_sc_format,
            .components = {
                VK_COMPONENT_SWIZZLE_IDENTITY,
                VK_COMPONENT_SWIZZLE_IDENTITY,
                VK_COMPONENT_SWIZZLE_IDENTITY,
                VK_COMPONENT_SWIZZLE_IDENTITY,
            },
            .subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 },
        };
        VK_CHECK(vkCreateImageView(s_device, &vi, NULL, &s_sc_views[i]));
    }
}

/* -----------------------------------------------------------------------
 * Render pass
 * ----------------------------------------------------------------------- */

static void create_render_pass(void)
{
    VkAttachmentDescription att = {
        .format         = s_sc_format,
        .samples        = VK_SAMPLE_COUNT_1_BIT,
        .loadOp         = VK_ATTACHMENT_LOAD_OP_CLEAR,
        .storeOp        = VK_ATTACHMENT_STORE_OP_STORE,
        .stencilLoadOp  = VK_ATTACHMENT_LOAD_OP_DONT_CARE,
        .stencilStoreOp = VK_ATTACHMENT_STORE_OP_DONT_CARE,
        .initialLayout  = VK_IMAGE_LAYOUT_UNDEFINED,
        .finalLayout    = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
    };
    VkAttachmentReference ref = {
        .attachment = 0,
        .layout     = VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL,
    };
    VkSubpassDescription sp = {
        .pipelineBindPoint    = VK_PIPELINE_BIND_POINT_GRAPHICS,
        .colorAttachmentCount = 1,
        .pColorAttachments    = &ref,
    };
    VkSubpassDependency dep = {
        .srcSubpass    = VK_SUBPASS_EXTERNAL,
        .dstSubpass    = 0,
        .srcStageMask  = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
        .srcAccessMask = 0,
        .dstStageMask  = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
        .dstAccessMask = VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT,
    };
    VkRenderPassCreateInfo rpi = {
        .sType           = VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO,
        .attachmentCount = 1, .pAttachments  = &att,
        .subpassCount    = 1, .pSubpasses    = &sp,
        .dependencyCount = 1, .pDependencies = &dep,
    };
    VK_CHECK(vkCreateRenderPass(s_device, &rpi, NULL, &s_render_pass));
}

/* -----------------------------------------------------------------------
 * Descriptor set layout
 * ----------------------------------------------------------------------- */

static void create_descriptor_set_layout(void)
{
    VkDescriptorSetLayoutBinding bindings[2] = {
        {
            .binding         = 0,
            .descriptorType  = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
            .descriptorCount = 1,
            .stageFlags      = VK_SHADER_STAGE_FRAGMENT_BIT,
        },
        {
            .binding         = 1,
            .descriptorType  = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
            .descriptorCount = 1,
            .stageFlags      = VK_SHADER_STAGE_FRAGMENT_BIT,
        },
    };
    VkDescriptorSetLayoutCreateInfo ci = {
        .sType        = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO,
        .bindingCount = 2,
        .pBindings    = bindings,
    };
    VK_CHECK(vkCreateDescriptorSetLayout(s_device, &ci, NULL, &s_dsl));
}

/* -----------------------------------------------------------------------
 * Pipeline
 * ----------------------------------------------------------------------- */

static VkShaderModule make_shader(const uint32_t *code, uint32_t len)
{
    VkShaderModuleCreateInfo ci = {
        .sType    = VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO,
        .codeSize = len,
        .pCode    = code,
    };
    VkShaderModule m;
    VK_CHECK(vkCreateShaderModule(s_device, &ci, NULL, &m));
    return m;
}

static void create_pipeline(void)
{
    VkShaderModule vert = make_shader(blit_vert_spv, blit_vert_spv_len);
    VkShaderModule frag = make_shader(blit_frag_spv, blit_frag_spv_len);

    VkPipelineShaderStageCreateInfo stages[2] = {
        {
            .sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
            .stage  = VK_SHADER_STAGE_VERTEX_BIT,
            .module = vert,
            .pName  = "main",
        },
        {
            .sType  = VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO,
            .stage  = VK_SHADER_STAGE_FRAGMENT_BIT,
            .module = frag,
            .pName  = "main",
        },
    };

    VkPipelineVertexInputStateCreateInfo vi = {
        .sType = VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO,
    };
    VkPipelineInputAssemblyStateCreateInfo ia = {
        .sType    = VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO,
        .topology = VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST,
    };

    VkViewport viewport = {
        .x        = 0.0f, .y        = 0.0f,
        .width    = (float)s_sc_extent.width,
        .height   = (float)s_sc_extent.height,
        .minDepth = 0.0f, .maxDepth = 1.0f,
    };
    VkRect2D scissor = { .offset = {0,0}, .extent = s_sc_extent };
    VkPipelineViewportStateCreateInfo vp = {
        .sType         = VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO,
        .viewportCount = 1, .pViewports = &viewport,
        .scissorCount  = 1, .pScissors  = &scissor,
    };

    VkPipelineRasterizationStateCreateInfo rs = {
        .sType       = VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO,
        .polygonMode = VK_POLYGON_MODE_FILL,
        .cullMode    = VK_CULL_MODE_NONE,
        .frontFace   = VK_FRONT_FACE_CLOCKWISE,
        .lineWidth   = 1.0f,
    };
    VkPipelineMultisampleStateCreateInfo ms = {
        .sType                = VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO,
        .rasterizationSamples = VK_SAMPLE_COUNT_1_BIT,
    };

    VkPipelineColorBlendAttachmentState cba = {
        .colorWriteMask = VK_COLOR_COMPONENT_R_BIT | VK_COLOR_COMPONENT_G_BIT |
                          VK_COLOR_COMPONENT_B_BIT | VK_COLOR_COMPONENT_A_BIT,
    };
    VkPipelineColorBlendStateCreateInfo cb = {
        .sType           = VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO,
        .attachmentCount = 1,
        .pAttachments    = &cba,
    };

    VkPipelineLayoutCreateInfo pli = {
        .sType          = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO,
        .setLayoutCount = 1,
        .pSetLayouts    = &s_dsl,
    };
    VK_CHECK(vkCreatePipelineLayout(s_device, &pli, NULL, &s_pipeline_layout));

    VkGraphicsPipelineCreateInfo gpi = {
        .sType               = VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO,
        .stageCount          = 2,
        .pStages             = stages,
        .pVertexInputState   = &vi,
        .pInputAssemblyState = &ia,
        .pViewportState      = &vp,
        .pRasterizationState = &rs,
        .pMultisampleState   = &ms,
        .pColorBlendState    = &cb,
        .layout              = s_pipeline_layout,
        .renderPass          = s_render_pass,
        .subpass             = 0,
    };
    VK_CHECK(vkCreateGraphicsPipelines(s_device, VK_NULL_HANDLE, 1, &gpi,
                                       NULL, &s_pipeline));

    vkDestroyShaderModule(s_device, vert, NULL);
    vkDestroyShaderModule(s_device, frag, NULL);
}

/* -----------------------------------------------------------------------
 * Framebuffers
 * ----------------------------------------------------------------------- */

static void create_framebuffers(void)
{
    s_sc_fbs = malloc(s_sc_count * sizeof(*s_sc_fbs));
    for (uint32_t i = 0; i < s_sc_count; i++) {
        VkFramebufferCreateInfo fi = {
            .sType           = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO,
            .renderPass      = s_render_pass,
            .attachmentCount = 1,
            .pAttachments    = &s_sc_views[i],
            .width           = s_sc_extent.width,
            .height          = s_sc_extent.height,
            .layers          = 1,
        };
        VK_CHECK(vkCreateFramebuffer(s_device, &fi, NULL, &s_sc_fbs[i]));
    }
}

/* -----------------------------------------------------------------------
 * Command pool + buffers
 * ----------------------------------------------------------------------- */

static void create_command_pool(void)
{
    VkCommandPoolCreateInfo ci = {
        .sType            = VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO,
        .queueFamilyIndex = s_gfx_family,
        .flags            = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT,
    };
    VK_CHECK(vkCreateCommandPool(s_device, &ci, NULL, &s_cmd_pool));

    VkCommandBufferAllocateInfo ai = {
        .sType              = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
        .commandPool        = s_cmd_pool,
        .level              = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
        .commandBufferCount = MAX_FRAMES_IN_FLIGHT,
    };
    VK_CHECK(vkAllocateCommandBuffers(s_device, &ai, s_cmd_bufs));
}

/* -----------------------------------------------------------------------
 * Sync objects
 * ----------------------------------------------------------------------- */

static void create_sync(void)
{
    VkSemaphoreCreateInfo si = { .sType = VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO };
    VkFenceCreateInfo fi = {
        .sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO,
        .flags = VK_FENCE_CREATE_SIGNALED_BIT,
    };
    for (int i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
        VK_CHECK(vkCreateSemaphore(s_device, &si, NULL, &s_sem_image_ready[i]));
        VK_CHECK(vkCreateFence(s_device, &fi, NULL, &s_fence[i]));
    }
    /* Render-done semaphores: one per swapchain image, indexed by s_image_idx.
     * Indexing by frame-in-flight is wrong — the presentation engine holds the
     * semaphore until the image is re-acquired, which may be > MAX_FRAMES later. */
    s_sem_render_done = malloc(s_sc_count * sizeof(VkSemaphore));
    for (uint32_t i = 0; i < s_sc_count; i++)
        VK_CHECK(vkCreateSemaphore(s_device, &si, NULL, &s_sem_render_done[i]));
}

/* -----------------------------------------------------------------------
 * Palette UBO
 * ----------------------------------------------------------------------- */

static void create_palette_buffer(void)
{
    make_buffer(PALETTE_UBO_SIZE,
                VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT,
                VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
                &s_pal_buf, &s_pal_mem);
    vkMapMemory(s_device, s_pal_mem, 0, PALETTE_UBO_SIZE, 0, &s_pal_map);

    /* Default palette: all black */
    memset(s_pal_map, 0, PALETTE_UBO_SIZE);
}

/* -----------------------------------------------------------------------
 * Index texture
 * ----------------------------------------------------------------------- */

static void create_index_texture(uint32_t w, uint32_t h)
{
    if (s_idx_image) {
        /* Destroy old resources before resize */
        vkDestroyImageView(s_device, s_idx_view, NULL);
        vkDestroyImage(s_device, s_idx_image, NULL);
        vkFreeMemory(s_device, s_idx_memory, NULL);
        vkUnmapMemory(s_device, s_idx_staging_mem);
        vkDestroyBuffer(s_device, s_idx_staging, NULL);
        vkFreeMemory(s_device, s_idx_staging_mem, NULL);
    }

    s_idx_w = w;
    s_idx_h = h;
    VkDeviceSize size = (VkDeviceSize)w * h;

    /* Device-local image */
    make_image(w, h, VK_FORMAT_R8_UNORM,
               VK_IMAGE_USAGE_TRANSFER_DST_BIT | VK_IMAGE_USAGE_SAMPLED_BIT,
               VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,
               &s_idx_image, &s_idx_memory);

    /* Transition to shader-read layout on first use */
    VkCommandBuffer cmd = begin_one_time();
    transition_image_layout(cmd, s_idx_image,
                            VK_IMAGE_LAYOUT_UNDEFINED,
                            VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL);
    end_one_time(cmd);

    /* Staging buffer — persistently mapped */
    make_buffer(size,
                VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
                VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
                &s_idx_staging, &s_idx_staging_mem);
    vkMapMemory(s_device, s_idx_staging_mem, 0, size, 0, &s_idx_staging_map);

    /* Image view */
    VkImageViewCreateInfo vi = {
        .sType      = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
        .image      = s_idx_image,
        .viewType   = VK_IMAGE_VIEW_TYPE_2D,
        .format     = VK_FORMAT_R8_UNORM,
        .components = {
            VK_COMPONENT_SWIZZLE_IDENTITY,
            VK_COMPONENT_SWIZZLE_IDENTITY,
            VK_COMPONENT_SWIZZLE_IDENTITY,
            VK_COMPONENT_SWIZZLE_IDENTITY,
        },
        .subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 },
    };
    VK_CHECK(vkCreateImageView(s_device, &vi, NULL, &s_idx_view));

    s_idx_first_upload = true;
}

/* -----------------------------------------------------------------------
 * Sampler
 * ----------------------------------------------------------------------- */

static void create_sampler(void)
{
    VkSamplerCreateInfo si = {
        .sType      = VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO,
        .magFilter  = VK_FILTER_NEAREST,
        .minFilter  = VK_FILTER_NEAREST,
        .mipmapMode = VK_SAMPLER_MIPMAP_MODE_NEAREST,
        .addressModeU = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
        .addressModeV = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
        .addressModeW = VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,
    };
    VK_CHECK(vkCreateSampler(s_device, &si, NULL, &s_sampler));
}

/* -----------------------------------------------------------------------
 * Descriptor pool + set
 * ----------------------------------------------------------------------- */

static void create_descriptor_set(void)
{
    VkDescriptorPoolSize ps[2] = {
        { VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER, 1 },
        { VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,         1 },
    };
    VkDescriptorPoolCreateInfo pi = {
        .sType         = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO,
        .maxSets       = 1,
        .poolSizeCount = 2,
        .pPoolSizes    = ps,
    };
    VK_CHECK(vkCreateDescriptorPool(s_device, &pi, NULL, &s_desc_pool));

    VkDescriptorSetAllocateInfo ai = {
        .sType              = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO,
        .descriptorPool     = s_desc_pool,
        .descriptorSetCount = 1,
        .pSetLayouts        = &s_dsl,
    };
    VK_CHECK(vkAllocateDescriptorSets(s_device, &ai, &s_desc_set));
}

static void update_descriptor_set(void)
{
    VkDescriptorImageInfo img_info = {
        .sampler     = s_sampler,
        .imageView   = s_idx_view,
        .imageLayout = VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL,
    };
    VkDescriptorBufferInfo buf_info = {
        .buffer = s_pal_buf,
        .offset = 0,
        .range  = PALETTE_UBO_SIZE,
    };
    VkWriteDescriptorSet writes[2] = {
        {
            .sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
            .dstSet          = s_desc_set,
            .dstBinding      = 0,
            .descriptorCount = 1,
            .descriptorType  = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
            .pImageInfo      = &img_info,
        },
        {
            .sType           = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET,
            .dstSet          = s_desc_set,
            .dstBinding      = 1,
            .descriptorCount = 1,
            .descriptorType  = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
            .pBufferInfo     = &buf_info,
        },
    };
    vkUpdateDescriptorSets(s_device, 2, writes, 0, NULL);
}

/* -----------------------------------------------------------------------
 * Public API
 * ----------------------------------------------------------------------- */

bool render_init(void)
{
    SDL_Window *win = platform_get_window();
    if (!win) { fprintf(stderr, "[render_vk] No window\n"); return false; }

    int win_w, win_h;
    SDL_Vulkan_GetDrawableSize(win, &win_w, &win_h);

    create_instance(win);

    if (!SDL_Vulkan_CreateSurface(win, s_instance, &s_surface)) {
        fprintf(stderr, "[render_vk] SDL_Vulkan_CreateSurface: %s\n", SDL_GetError());
        return false;
    }

    pick_device();
    create_device();
    create_swapchain(win_w, win_h);
    create_render_pass();
    create_descriptor_set_layout();
    create_sampler();
    create_palette_buffer();
    create_command_pool();
    /* Index texture created on first render_blit_indexed call */
    create_descriptor_set();
    create_pipeline();
    create_framebuffers();
    create_sync();

    fprintf(stdout, "[render_vk] Vulkan ready (%ux%u, %u swapchain images)\n",
            s_sc_extent.width, s_sc_extent.height, s_sc_count);
    return true;
}

void render_shutdown(void)
{
    vkDeviceWaitIdle(s_device);

    for (int i = 0; i < MAX_FRAMES_IN_FLIGHT; i++) {
        vkDestroySemaphore(s_device, s_sem_image_ready[i], NULL);
        vkDestroyFence(s_device, s_fence[i], NULL);
    }
    for (uint32_t i = 0; i < s_sc_count; i++)
        vkDestroySemaphore(s_device, s_sem_render_done[i], NULL);
    free(s_sem_render_done);

    for (uint32_t i = 0; i < s_sc_count; i++) {
        vkDestroyFramebuffer(s_device, s_sc_fbs[i], NULL);
        vkDestroyImageView(s_device, s_sc_views[i], NULL);
    }
    free(s_sc_fbs); free(s_sc_views); free(s_sc_images);

    if (s_idx_image) {
        vkDestroyImageView(s_device, s_idx_view, NULL);
        vkDestroyImage(s_device, s_idx_image, NULL);
        vkFreeMemory(s_device, s_idx_memory, NULL);
        vkUnmapMemory(s_device, s_idx_staging_mem);
        vkDestroyBuffer(s_device, s_idx_staging, NULL);
        vkFreeMemory(s_device, s_idx_staging_mem, NULL);
    }

    vkUnmapMemory(s_device, s_pal_mem);
    vkDestroyBuffer(s_device, s_pal_buf, NULL);
    vkFreeMemory(s_device, s_pal_mem, NULL);

    vkDestroyDescriptorPool(s_device, s_desc_pool, NULL);
    vkDestroyDescriptorSetLayout(s_device, s_dsl, NULL);
    vkDestroySampler(s_device, s_sampler, NULL);
    vkDestroyPipeline(s_device, s_pipeline, NULL);
    vkDestroyPipelineLayout(s_device, s_pipeline_layout, NULL);
    vkDestroyRenderPass(s_device, s_render_pass, NULL);
    vkDestroyCommandPool(s_device, s_cmd_pool, NULL);
    vkDestroySwapchainKHR(s_device, s_swapchain, NULL);
    vkDestroyDevice(s_device, NULL);
    vkDestroySurfaceKHR(s_instance, s_surface, NULL);
    vkDestroyInstance(s_instance, NULL);
}

void render_begin_frame(void)
{
    vkWaitForFences(s_device, 1, &s_fence[s_frame], VK_TRUE, UINT64_MAX);

    VkResult r = vkAcquireNextImageKHR(s_device, s_swapchain, UINT64_MAX,
                                       s_sem_image_ready[s_frame],
                                       VK_NULL_HANDLE, &s_image_idx);
    if (r == VK_ERROR_OUT_OF_DATE_KHR || r == VK_SUBOPTIMAL_KHR) {
        /* TODO: recreate swapchain on resize */
        fprintf(stderr, "[render_vk] Swapchain out of date — resize not yet handled\n");
    }

    vkResetFences(s_device, 1, &s_fence[s_frame]);
    vkResetCommandBuffer(s_cmd_bufs[s_frame], 0);
}

void render_end_frame(void)
{
    VkCommandBuffer cmd = s_cmd_bufs[s_frame];

    VkCommandBufferBeginInfo bi = {
        .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
    };
    vkBeginCommandBuffer(cmd, &bi);

    /* Upload index texture if dirty */
    if (s_pending_blit && s_idx_image) {
        VkImageLayout from = s_idx_first_upload
            ? VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL
            : VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;

        if (!s_idx_first_upload)
            transition_image_layout(cmd, s_idx_image, from,
                                    VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL);

        VkBufferImageCopy region = {
            .imageSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 },
            .imageExtent      = { s_idx_w, s_idx_h, 1 },
        };
        vkCmdCopyBufferToImage(cmd, s_idx_staging, s_idx_image,
                               VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL, 1, &region);

        transition_image_layout(cmd, s_idx_image,
                                VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,
                                VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);

        if (s_idx_first_upload) {
            /* First upload: bind the image into the descriptor set now */
            update_descriptor_set();
            s_idx_first_upload = false;
        }

        s_pending_blit = false;
    }

    /* Render pass */
    VkClearValue clear = { .color = {{0,0,0,1}} };
    VkRenderPassBeginInfo rpi = {
        .sType           = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO,
        .renderPass      = s_render_pass,
        .framebuffer     = s_sc_fbs[s_image_idx],
        .renderArea      = { .extent = s_sc_extent },
        .clearValueCount = 1,
        .pClearValues    = &clear,
    };
    vkCmdBeginRenderPass(cmd, &rpi, VK_SUBPASS_CONTENTS_INLINE);

    if (!s_idx_first_upload) {
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, s_pipeline);
        vkCmdBindDescriptorSets(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS,
                                s_pipeline_layout, 0, 1, &s_desc_set, 0, NULL);
        vkCmdDraw(cmd, 3, 1, 0, 0);
    }

    vkCmdEndRenderPass(cmd);
    vkEndCommandBuffer(cmd);

    VkPipelineStageFlags wait_stage = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
    VkSubmitInfo si = {
        .sType                = VK_STRUCTURE_TYPE_SUBMIT_INFO,
        .waitSemaphoreCount   = 1,
        .pWaitSemaphores      = &s_sem_image_ready[s_frame],
        .pWaitDstStageMask    = &wait_stage,
        .commandBufferCount   = 1,
        .pCommandBuffers      = &cmd,
        .signalSemaphoreCount = 1,
        .pSignalSemaphores    = &s_sem_render_done[s_image_idx],
    };
    VK_CHECK(vkQueueSubmit(s_gfx_queue, 1, &si, s_fence[s_frame]));

    VkPresentInfoKHR pi = {
        .sType              = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR,
        .waitSemaphoreCount = 1,
        .pWaitSemaphores    = &s_sem_render_done[s_image_idx],
        .swapchainCount     = 1,
        .pSwapchains        = &s_swapchain,
        .pImageIndices      = &s_image_idx,
    };
    vkQueuePresentKHR(s_present_queue, &pi);

    s_frame = (s_frame + 1) % MAX_FRAMES_IN_FLIGHT;
    s_pending_palette = false;
}

void render_set_palette(const Rgb8 *palette_256)
{
    /* Palette UBO layout (std140): 256 × vec4, each vec4 = {r,g,b,1} floats */
    float *dst = (float *)s_pal_map;
    for (int i = 0; i < 256; i++) {
        dst[i * 4 + 0] = palette_256[i].r / 255.0f;
        dst[i * 4 + 1] = palette_256[i].g / 255.0f;
        dst[i * 4 + 2] = palette_256[i].b / 255.0f;
        dst[i * 4 + 3] = 1.0f;
    }
    s_pending_palette = true;
}

void render_blit_indexed(const uint8_t *pixels, uint32_t w, uint32_t h)
{
    if (w != s_idx_w || h != s_idx_h)
        create_index_texture(w, h);

    memcpy(s_idx_staging_map, pixels, (size_t)w * h);
    s_pending_blit = true;
}
