# embed_spv.cmake — converts a .spv file into a C header with a uint32_t array.
# Called via cmake -P, expects INPUT, OUTPUT, VAR to be set by the caller.
#
# Usage in CMakeLists.txt:
#   cmake -DINPUT=foo.spv -DOUTPUT=foo_spv.h -DVAR=foo_spv -P cmake/embed_spv.cmake

file(READ "${INPUT}" raw HEX)

# SPIR-V is always a multiple of 4 bytes; each 8 hex chars = one uint32_t
string(LENGTH "${raw}" hex_len)
math(EXPR word_count "${hex_len} / 8")

set(words "")
foreach(i RANGE 1 ${word_count})
    math(EXPR off "( ${i} - 1 ) * 8")
    string(SUBSTRING "${raw}" ${off} 8 chunk)
    # SPIR-V is little-endian: file bytes b0 b1 b2 b3 represent the uint32 value
    # 0x{b3}{b2}{b1}{b0}.  Emit the correct host-endian literal so that when C
    # stores it in memory the original byte sequence is preserved.
    string(SUBSTRING "${chunk}" 0 2 b0)
    string(SUBSTRING "${chunk}" 2 2 b1)
    string(SUBSTRING "${chunk}" 4 2 b2)
    string(SUBSTRING "${chunk}" 6 2 b3)
    string(APPEND words "0x${b3}${b2}${b1}${b0}U,")
endforeach()

math(EXPR byte_len "${word_count} * 4")

file(WRITE "${OUTPUT}"
"/* auto-generated by cmake/embed_spv.cmake — do not edit */
static const uint32_t ${VAR}[] = {
${words}
};
static const uint32_t ${VAR}_len = ${byte_len}U;
")
